name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v4
        with:
          repository: medyagh/local-dev-example-with-minikube
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Build image
        run: |
          minikube image build -t local/devex:v1 .
      - name: Deploy to minikube
        run: |
          kubectl apply -f deploy/k8s.yaml
          kubectl wait --for=condition=ready pod -l app=local-devex
      - name: Test service URLs
        run: |
          minikube service list
          minikube service local-devex-svc --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service local-devex-svc --url)/version

      - name: Run Dastardly Action Step for ginandjuice.shop
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://ginandjuice.shop'
